spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/comfortsoft-task
    username: postgres
    password:
#    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog.yml
    enabled: true
